apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-binding
  labels:
    app.kubernetes.io/part-of: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd-test
roleRef:
  kind: ClusterRole
  name: argocd-clusterrole
  apiGroup: rbac.authorization.k8s.io
