apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-external-secrets-binding
  namespace: external-secrets-test
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd-test
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
