apiVersion: eksctl.io/v1alpha5
kind: ExternalSecret
metadata:
  name: example-secret-for-gcp-alayan-project
  namespace: external-secrets-test
spec:
  backendType: secretsManager
  data:
    - secretKey: my-secret-key
      remoteRef:
        key: "my-secret-name"
