apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example-gcp-secret
  namespace: external-secrets-test
spec:
  backendType: gcpSecretsManager
  data:
    - secretKey: my-gcp-secret-key
      remoteRef:
        key: "projects/lokalee-testing/secrets/test-argocd/versions/latest"
