apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-gcp-secret
  namespace: external-secrets-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secretstore
    kind: SecretStore
  target:
    name: my-synced-secret
    creationPolicy: Owner
  data:
    - secretKey: my-gcp-secret-key
      remoteRef:
        key: "projects/lokalee-testing/secrets/test-argocd/versions/latest"
