apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-secret
  namespace: external-secrets-testing
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: my-gcp-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: my-db-secret
        property: username
    - secretKey: DB_PASS
      remoteRef:
        key: my-db-secret
        property: password
