apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-gcp-secret
  namespace: external-secrets-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: my-kubernetes-secret
    creationPolicy: Owner
  data:
  - secretKey: mohammad alayan # Replace with your GCP Secret Manager key
    remoteRef:
      key: test-argocd # Replace with your GCP secret ID
