apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: external-secrets-test
spec:
  provider:
    gcp:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-service-account
            key: service-account-key.json
      projectID: lokalee-testing # Replace this with your GCP project ID
