apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: external-secrets-testing
spec:
  provider:
    gcpsm:
      projectID: lokalee-testing
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-credentials
            key: secret-access-key
